# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: lab.devsecops.com

steps:
- task: Bash@3
  displayName: Fortify Rulepack Gate
  inputs:
    targetType: 'inline'
    script: |
      # Defini as variáveis
      fortify_url="https://lab.devsecops.com:8443/ssc/api/v1"
      fortify_token="YWE4ZDgwM2ItNDQ0Yy00ZDkwLWFkOTItZDc3YmEzM2IyYzk4"
      app_name="configuration"
      app_version="dev"
      rulepack_gate=""
      
      # Defini os cabeçalhos
      headers=(-H "Accept: application/json" -H "Authorization: FortifyToken $fortify_token")
      
      # Fazendo a requisição HTTP no endpoint que lista as aplicações
      response=$(curl -sS -k -w "\n%{http_code}" "${fortify_url}/projects?start=0&limit=200&q=name%3A${app_name}&fulltextsearch=false" "${headers[@]}")
      status_code=$(echo "$response" | tail -n1)
      response_body=$(echo "$response" | sed '$d')
      if [ "$status_code" -ne 200 ]; then
          echo "Erro na request /projects?start=0&limit=200&q=name%3${app_name}&fulltextsearch=false return code $status_code"
          exit 1
      fi
      app_id=$(echo "$response_body" | jq '.data[0].id')
      
      # Fazendo a requisição HTTP no endpoint que lista as versões de aplicações
      response=$(curl -sS -k -w "\n%{http_code}" "${fortify_url}/projects/${app_id}/versions?start=0&limit=0&q=name%3A${app_version}&fulltextsearch=false" "${headers[@]}")
      status_code=$(echo "$response" | tail -n1)
      response_body=$(echo "$response" | sed '$d')
      if [ "$status_code" -ne 200 ]; then
          echo "Erro na request /projects/${app_id}/versions?start=0&limit=0 return code $status_code"
          exit 1
      fi
      version_id=$(echo "$response_body" | jq '.data[0].id')

      # Fazendo a requisição HTTP no endpoint que lista as issues da versão da aplicação
      response=$(curl -sS -k -w "\n%{http_code}" "${fortify_url}/projectVersions/${version_id}/issues?start=0&limit=0&fields=issueName%2Cfriority%2CprimaryTag%2CissueInstanceId%2CprimaryRuleGuid&showhidden=false&showremoved=false&showsuppressed=false&showshortfilenames=false" "${headers[@]}")
      status_code=$(echo "$response" | tail -n1)
      response_body=$(echo "$response" | sed '$d')
      if [ "$status_code" -ne 200 ]; then
          echo "Erro na request /projectVersions/${version_id}/issues?start=0&limit=0&fields=issueName%2Cfriority%2CprimaryTag%2CissueInstanceId%2CprimaryRuleGuid&showhidden=false&showremoved=false&showsuppressed=false&showshortfilenames=false return code $status_code"
          exit 1
      fi
      issues=$(echo "$response_body" | jq '.')
