# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main
pool:
  name: lab.devsecops.com
steps:
- task: Bash@3
  displayName: Fortify Rulepack Gate
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash

      # Define variáveis
      fortify_url="https://lab.devsecops.com:8443/ssc/api/v1"
      fortify_token="YWE4ZDgwM2ItNDQ0Yy00ZDkwLWFkOTItZDc3YmEzM2IyYzk4"
      app_name="configuration"
      app_version="dev"

      # Cabeçalhos da requisição HTTP
      headers=(-H "Accept: application/json" -H "Authorization: FortifyToken $fortify_token")

      # Função para executar consulta SQL e lidar com erros
      execute_sql_query() {
          local query="$1"
          sqlcmd -S "$DB_SERVER" -U "$DB_USER" -P "$DB_PASS" -d "$DB_NAME" -Q "$query" -s"," -W | tr -d '\r'
      }

      # Requisição HTTP para listar aplicações
      response=$(curl -sS -k -w "\n%{http_code}" "${fortify_url}/projects?start=0&limit=200&q=name%3A${app_name}&fulltextsearch=false" "${headers[@]}")
      status_code=$(echo "$response" | tail -n1)
      response_body=$(echo "$response" | sed '$d')
      if [ "$status_code" -ne 200 ]; then
          echo "Erro na requisição /projects. Código de retorno $status_code"
          exit 1
      fi
      app_id=$(echo "$response_body" | jq -r '.data[0].id')

      # Requisição HTTP para listar versões da aplicação
      response=$(curl -sS -k -w "\n%{http_code}" "${fortify_url}/projects/${app_id}/versions?start=0&limit=0&q=name%3A${app_version}&fulltextsearch=false" "${headers[@]}")
      status_code=$(echo "$response" | tail -n1)
      response_body=$(echo "$response" | sed '$d')
      if [ "$status_code" -ne 200 ]; then
          echo "Erro na requisição /projects/${app_id}/versions. Código de retorno $status_code"
          exit 1
      fi
      version_id=$(echo "$response_body" | jq -r '.data[0].id')

      # Requisição HTTP para listar issues da versão da aplicação
      response=$(curl -sS -k -w "\n%{http_code}" "${fortify_url}/projectVersions/${version_id}/issues?start=0&limit=0&fields=issueName%2Cfriority%2CprimaryTag%2CissueInstanceId%2CprimaryRuleGuid&showhidden=false&showremoved=false&showsuppressed=false&showshortfilenames=false" "${headers[@]}")
      status_code=$(echo "$response" | tail -n1)
      response_body=$(echo "$response" | sed '$d')
      if [ "$status_code" -ne 200 ]; then
          echo "Erro na requisição /projectVersions/${version_id}/issues. Código de retorno $status_code"
          exit 1
      fi

      # Processa o JSON e extrai os primaryRuleGuids
      primaryRuleGuids=$(echo "$response_body" | jq -r '.data[].primaryRuleGuid')

      # Configurações do banco de dados
      DB_SERVER="lab.devsecops.com,1435"
      DB_USER="sa"
      DB_PASS="t3cn0l0gi4!"
      DB_NAME="sscdb"

      # Itera sobre cada primaryRuleGuid
      for guid in $primaryRuleGuids; do
          echo "Consulta para Issue primaryRuleGuid: $guid"

          # Executa a consulta SQL para obter rulepack_id
          rulepack_ids=$(execute_sql_query "
              SELECT rulepack_id
              FROM ruledescription
              WHERE guid = '$guid'
          ")

          # Verifica se rulepack_ids não está vazio antes de processar
          if [ -n "$rulepack_ids" ]; then
              # Converte a lista separada por vírgulas em um array
              IFS=',' read -r -a rulepack_array <<< "$rulepack_ids"

              # Itera sobre cada rulepack_id
              for rulepack_id in "${rulepack_array[@]}"; do
                  # Executa consulta SQL para obter detalhes do rulepack
                  rulepack_result=$(execute_sql_query "
                      SELECT name, versionNumber, rulepackType, locale, progLanguage
                      FROM rulepack
                      WHERE id = $rulepack_id
                  ")

                  # Verifica se algum resultado foi retornado
                  if [ -n "$rulepack_result" ]; then
                      echo "$rulepack_result"
                  else
                      echo "Nenhum rulepack encontrado para o id: $rulepack_id"
                  fi
              done
          else
              echo "Nenhum ID de rulepack encontrado para o guid $guid."
          fi
      done
